// <auto-generated />
using System;
using EvoAITest.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvoAITest.Core.Migrations
{
    [DbContext(typeof(EvoAIDbContext))]
    [Migration("20260122115700_AddAnalyticsAlerting")]
    partial class AddAnalyticsAlerting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecordedInteractionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssertionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int?>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("GeneratedCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeInTest")
                        .HasColumnType("bit");

                    b.Property<string>("InputValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("IntentConfidence")
                        .HasColumnType("float");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("IX_RecordedInteractions_ActionType");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_RecordedInteractions_SessionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_RecordedInteractions_Timestamp");

                    b.HasIndex("SessionId", "SequenceNumber")
                        .HasDatabaseName("IX_RecordedInteractions_SessionId_Sequence");

                    b.ToTable("RecordedInteractions", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecordingSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GeneratedTestCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StartUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViewportHeight")
                        .HasColumnType("int");

                    b.Property<int>("ViewportWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_RecordingSessions_CreatedBy");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_RecordingSessions_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RecordingSessions_Status");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("IX_RecordingSessions_Status_StartedAt");

                    b.ToTable("RecordingSessions", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecoveryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("RecoveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecoveryActions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecoveryStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Selector")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ErrorType")
                        .HasDatabaseName("IX_RecoveryHistory_ErrorType");

                    b.HasIndex("RecoveredAt")
                        .HasDatabaseName("IX_RecoveryHistory_RecoveredAt");

                    b.HasIndex("Success")
                        .HasDatabaseName("IX_RecoveryHistory_Success");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_RecoveryHistory_TaskId");

                    b.HasIndex("ErrorType", "Success")
                        .HasDatabaseName("IX_RecoveryHistory_ErrorType_Success");

                    b.ToTable("RecoveryHistory", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.SelectorHealingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("HealedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HealedSelector")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HealingStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalSelector")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HealedAt");

                    b.HasIndex("HealingStrategy");

                    b.HasIndex("Success");

                    b.HasIndex("TaskId");

                    b.ToTable("SelectorHealingHistory", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.WaitHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ActualWaitMs")
                        .HasColumnType("int");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Selector")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("int");

                    b.Property<string>("WaitCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("Success");

                    b.HasIndex("TaskId");

                    b.ToTable("WaitHistory", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Analytics.AlertHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcknowledgmentNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ActualValue")
                        .HasColumnType("float");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChannelsNotified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationSuccess")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Acknowledged")
                        .HasDatabaseName("IX_AlertHistory_Acknowledged")
                        .HasFilter("[Acknowledged] = 0");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("IX_AlertHistory_AlertRuleId");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_AlertHistory_RecordingSessionId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_AlertHistory_Severity");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("IX_AlertHistory_TriggeredAt");

                    b.HasIndex("AlertRuleId", "TriggeredAt")
                        .HasDatabaseName("IX_AlertHistory_RuleId_Triggered");

                    b.ToTable("AlertHistory", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Analytics.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.Property<int>("ThrottleMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_AlertRules_Enabled")
                        .HasFilter("[Enabled] = 1");

                    b.HasIndex("LastTriggeredAt")
                        .HasDatabaseName("IX_AlertRules_LastTriggered");

                    b.HasIndex("Metric")
                        .HasDatabaseName("IX_AlertRules_Metric");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_AlertRules_RecordingSessionId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_AlertRules_Severity");

                    b.HasIndex("Enabled", "Metric")
                        .HasDatabaseName("IX_AlertRules_Enabled_Metric")
                        .HasFilter("[Enabled] = 1");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Analytics.FlakyTestAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AnalysisConfidence")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("AverageTimeToFailure")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsistentFailureCount")
                        .HasColumnType("int");

                    b.Property<int>("ConsistentPassCount")
                        .HasColumnType("int");

                    b.Property<double>("DurationVariability")
                        .HasColumnType("float");

                    b.Property<long?>("ExecutionDurationStdDev")
                        .HasColumnType("bigint");

                    b.Property<double>("FlakinessScore")
                        .HasColumnType("float");

                    b.Property<int>("FlakyFailureCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastExecutionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PassRate")
                        .HasColumnType("float");

                    b.Property<string>("Patterns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RootCauses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt")
                        .HasDatabaseName("IX_FlakyTestAnalyses_AnalyzedAt");

                    b.HasIndex("FlakinessScore")
                        .HasDatabaseName("IX_FlakyTestAnalyses_FlakinessScore");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_FlakyTestAnalyses_RecordingSessionId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_FlakyTestAnalyses_Severity");

                    b.HasIndex("RecordingSessionId", "FlakinessScore")
                        .HasDatabaseName("IX_FlakyTestAnalyses_RecordingId_Score");

                    b.ToTable("FlakyTestAnalyses", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Analytics.TestTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AverageDurationMs")
                        .HasColumnType("bigint");

                    b.Property<double>("AverageStepsPerTest")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompilationErrors")
                        .HasColumnType("int");

                    b.Property<long>("DurationStdDev")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedExecutions")
                        .HasColumnType("int");

                    b.Property<int>("FlakyTestCount")
                        .HasColumnType("int");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MaxDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MinDurationMs")
                        .HasColumnType("bigint");

                    b.Property<double>("PassRate")
                        .HasColumnType("float");

                    b.Property<int>("PassedExecutions")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetriedTests")
                        .HasColumnType("int");

                    b.Property<int>("SkippedExecutions")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("int");

                    b.Property<int>("UniqueTestCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Interval")
                        .HasDatabaseName("IX_TestTrends_Interval");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_TestTrends_RecordingSessionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_TestTrends_Timestamp");

                    b.HasIndex("Interval", "Timestamp")
                        .HasDatabaseName("IX_TestTrends_Interval_Timestamp");

                    b.HasIndex("RecordingSessionId", "Timestamp")
                        .HasDatabaseName("IX_TestTrends_RecordingId_Timestamp");

                    b.HasIndex("RecordingSessionId", "Interval", "Timestamp")
                        .HasDatabaseName("IX_TestTrends_RecordingId_Interval_Timestamp");

                    b.ToTable("TestTrends", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.AutomationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NaturalLanguagePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VisualCheckpoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("AutomationTasks", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Execution.TestExecutionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artifacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilationErrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Environment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_TestExecutionResults_RecordingSessionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_TestExecutionResults_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TestExecutionResults_Status");

                    b.HasIndex("RecordingSessionId", "Status")
                        .HasDatabaseName("IX_TestExecutionResults_RecordingSessionId_Status");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("IX_TestExecutionResults_Status_StartedAt");

                    b.ToTable("TestExecutionResults", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Execution.TestExecutionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artifacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConsoleOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordingSessionId")
                        .HasDatabaseName("IX_TestExecutionSessions_RecordingSessionId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_TestExecutionSessions_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TestExecutionSessions_Status");

                    b.ToTable("TestExecutionSessions", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.ExecutionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FinalOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenshotUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StepResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisualCheckpointsFailed")
                        .HasColumnType("int");

                    b.Property<int>("VisualCheckpointsPassed")
                        .HasColumnType("int");

                    b.Property<string>("VisualComparisonResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionStatus");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TaskId");

                    b.ToTable("ExecutionHistory", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.VisualBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BaselinePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CheckpointName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GitCommit")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PreviousBaselineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Viewport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GitBranch");

                    b.HasIndex("PreviousBaselineId");

                    b.HasIndex("TaskId", "CheckpointName", "Environment", "Browser")
                        .IsUnique();

                    b.HasIndex("TaskId", "CheckpointName", "Environment", "Browser", "Viewport")
                        .IsUnique();

                    b.ToTable("VisualBaselines", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Models.VisualComparisonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BaselineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaselinePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckpointName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ComparedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiffPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DifferencePercentage")
                        .HasColumnType("float");

                    b.Property<string>("DifferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExecutionHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("PixelsDifferent")
                        .HasColumnType("int");

                    b.Property<string>("Regions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SsimScore")
                        .HasColumnType("float");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Tolerance")
                        .HasColumnType("float");

                    b.Property<int>("TotalPixels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId");

                    b.HasIndex("ComparedAt");

                    b.HasIndex("ExecutionHistoryId");

                    b.HasIndex("Passed");

                    b.HasIndex("TaskId");

                    b.ToTable("VisualComparisonResults", (string)null);
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecordedInteractionEntity", b =>
                {
                    b.HasOne("EvoAITest.Core.Data.Models.RecordingSessionEntity", "Session")
                        .WithMany("Interactions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecoveryHistory", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.SelectorHealingHistory", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.WaitHistory", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Models.Analytics.AlertHistory", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.Analytics.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("EvoAITest.Core.Models.ExecutionHistory", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Models.VisualBaseline", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.VisualBaseline", null)
                        .WithMany()
                        .HasForeignKey("PreviousBaselineId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Models.VisualComparisonResult", b =>
                {
                    b.HasOne("EvoAITest.Core.Models.VisualBaseline", "Baseline")
                        .WithMany()
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EvoAITest.Core.Models.ExecutionHistory", "ExecutionHistory")
                        .WithMany()
                        .HasForeignKey("ExecutionHistoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EvoAITest.Core.Models.AutomationTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baseline");

                    b.Navigation("ExecutionHistory");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EvoAITest.Core.Data.Models.RecordingSessionEntity", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("EvoAITest.Core.Models.AutomationTask", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
